name: Deploy Javadoc and Mutation Testing Report to GitHub Page 🚀

on:
  push:
    branches:
      - master
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          cache: maven

      - name: Generate Javadoc with Maven
        run: mvn javadoc:aggregate
        shell: bash

      - name: Generate mutation testing report with Maven
        run: mvn -DwithHistory test-compile org.pitest:pitest-maven:mutationCoverage
        shell: bash

      - name: Deploy to GitHub Page 🚀 with Maven
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: javadoc
          clean: true
          folder: target/pit-reports
          target-folder: pitest

      - name: Deploy to GitHub Page 🚀 with Maven
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: javadoc
          clean: true
          folder: target/site/apidocs
          target-folder: javadoc